create type public.asset_authorization_type as enum ('SUBLEASE');
create type public.asset_authorization_status as enum ('PENDING','AUTHORIZED','REJECTED','REVOKED','EXPIRED');
create table public.asset_authorizations(
 id uuid primary key default gen_random_uuid(),
 administration_id uuid not null references public.administrations(id) on delete cascade,
 rental_subject_id uuid not null,
 authorization_type public.asset_authorization_type not null default 'SUBLEASE',
 source_relationship_id uuid not null,
 grantor_person_id uuid not null references public.people(id) on delete restrict,
 grantee_person_id uuid not null references public.people(id) on delete restrict,
 status public.asset_authorization_status not null default 'PENDING',
 requested_at timestamptz not null default now(),
 decided_at timestamptz,
 valid_from date,
 valid_until date,
 evidence_file_id uuid references public.files(id) on delete set null,
 decision_notes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 constraint asset_authorizations_subject_fk foreign key(administration_id,rental_subject_id) references public.rental_subjects(administration_id,id) on delete cascade,
 constraint asset_authorizations_source_fk foreign key(administration_id,source_relationship_id) references public.rental_relationships(administration_id,id) on delete restrict,
 constraint asset_authorization_dates_ck check(valid_until is null or valid_from is null or valid_until>=valid_from),
 constraint asset_authorization_decision_ck check((status='PENDING' and decided_at is null) or status<>'PENDING')
);
create index asset_authorizations_admin_idx on public.asset_authorizations(administration_id);
create index asset_authorizations_subject_idx on public.asset_authorizations(rental_subject_id);
create index asset_authorizations_source_idx on public.asset_authorizations(source_relationship_id);
create index asset_authorizations_grantor_idx on public.asset_authorizations(grantor_person_id);
create index asset_authorizations_grantee_idx on public.asset_authorizations(grantee_person_id);
create unique index asset_authorizations_one_pending_uq on public.asset_authorizations(rental_subject_id,grantee_person_id,source_relationship_id) where status='PENDING';
alter table public.asset_authorizations enable row level security;
grant select on public.asset_authorizations to authenticated;
revoke insert,update,delete on public.asset_authorizations from anon,authenticated;
create policy asset_authorizations_select on public.asset_authorizations for select to authenticated using(public.is_administration_member(administration_id) or grantor_person_id=public.current_person_id() or grantee_person_id=public.current_person_id());
alter table public.asset_rights add constraint asset_rights_authorization_fk foreign key(authorization_id) references public.asset_authorizations(id) on delete restrict;
alter table public.asset_rights drop constraint sublease_requires_source_ck;
alter table public.asset_rights add constraint sublease_requires_source_and_authorization_ck check(right_type<>'AUTHORIZED_SUBLEASE' or (source_relationship_id is not null and authorization_id is not null));
create or replace function public.request_parking_sublease_authorization(p_rental_subject_id uuid,p_source_relationship_id uuid,p_grantor_person_id uuid,p_grantee_person_id uuid,p_token_hash text,p_expires_at timestamptz,p_valid_from date default null,p_valid_until date default null) returns public.asset_authorizations language plpgsql security definer set search_path='' as $$ declare s public.rental_subjects; r public.rental_relationships; a public.asset_authorizations; actor uuid; begin select * into s from public.rental_subjects where id=p_rental_subject_id; if not found or s.subject_type<>'PARKING' then raise exception 'PARKING_SUBJECT_REQUIRED'; end if; if public.can_manage_administration(s.administration_id) is not true then raise exception 'MANAGEMENT_ACCESS_REQUIRED'; end if; select * into r from public.rental_relationships where id=p_source_relationship_id and administration_id=s.administration_id; if not found or r.status not in('ACTIVE','ENDING') then raise exception 'ACTIVE_SOURCE_RELATIONSHIP_REQUIRED'; end if; if not exists(select 1 from public.rental_relationship_subjects rs where rs.rental_relationship_id=r.id and rs.rental_subject_id=s.id) then raise exception 'PARKING_NOT_IN_SOURCE_RELATIONSHIP'; end if; if not exists(select 1 from public.rental_participants rp where rp.rental_relationship_id=r.id and rp.person_id=p_grantee_person_id and rp.participation_type='TENANT' and rp.status='ACTIVE') then raise exception 'GRANTEE_MUST_BE_ACTIVE_SOURCE_TENANT'; end if; if p_valid_until is not null and p_valid_from is not null and p_valid_until<p_valid_from then raise exception 'INVALID_AUTHORIZATION_DATES'; end if; if p_expires_at<=now() then raise exception 'SECURE_ACTION_EXPIRY_REQUIRED'; end if; if p_token_hash !~ '^[0-9a-fA-F]{64}$' then raise exception 'INVALID_TOKEN_HASH'; end if; select person_id into actor from public.accounts where auth_user_id=auth.uid(); insert into public.asset_authorizations(administration_id,rental_subject_id,source_relationship_id,grantor_person_id,grantee_person_id,valid_from,valid_until) values(s.administration_id,s.id,r.id,p_grantor_person_id,p_grantee_person_id,p_valid_from,p_valid_until) returning * into a; insert into public.secure_actions(administration_id,person_id,rental_relationship_id,action_type,status,resource_type,resource_id,token_hash,expires_at,created_by_person_id) values(s.administration_id,p_grantor_person_id,r.id,'SUBLEASE_AUTHORIZATION','PENDING','ASSET_AUTHORIZATION',a.id,lower(p_token_hash),p_expires_at,actor); return a; end $$;
create or replace function public.decide_parking_sublease_authorization(p_token text,p_approve boolean,p_notes text default null) returns public.asset_authorizations language plpgsql security definer set search_path='' as $$ declare h text; sa public.secure_actions; a public.asset_authorizations; actor uuid; begin if p_token is null or length(btrim(p_token))<32 then raise exception 'INVALID_TOKEN'; end if; h:=encode(extensions.digest(convert_to(p_token,'UTF8'),'sha256'),'hex'); select * into sa from public.secure_actions where token_hash=h and action_type='SUBLEASE_AUTHORIZATION' and resource_type='ASSET_AUTHORIZATION' for update; if not found then raise exception 'ACTION_NOT_FOUND'; end if; if sa.status<>'PENDING' then raise exception 'ACTION_NOT_PENDING'; end if; if sa.revoked_at is not null then raise exception 'ACTION_REVOKED'; end if; if sa.expires_at<=now() then raise exception 'ACTION_EXPIRED'; end if; select * into a from public.asset_authorizations where id=sa.resource_id for update; if not found or a.status<>'PENDING' then raise exception 'AUTHORIZATION_NOT_PENDING'; end if; actor:=public.current_person_id(); if actor is not null and actor<>a.grantor_person_id then raise exception 'WRONG_GRANTOR_ACCOUNT'; end if; update public.asset_authorizations set status=case when p_approve then 'AUTHORIZED'::public.asset_authorization_status else 'REJECTED'::public.asset_authorization_status end,decided_at=now(),decision_notes=nullif(btrim(p_notes),''),updated_at=now() where id=a.id returning * into a; update public.secure_actions set status='COMPLETED',completed_at=now() where id=sa.id; insert into public.acceptances(administration_id,person_id,rental_relationship_id,document_type,document_version,purpose,subject_type,subject_id,accepted_at,method,evidence) values(a.administration_id,a.grantor_person_id,a.source_relationship_id,'SUBLEASE_AUTHORIZATION','1',case when p_approve then 'AUTHORIZE_SUBLEASE' else 'REJECT_SUBLEASE' end,'ASSET_AUTHORIZATION',a.id,now(),'SECURE_LINK',jsonb_build_object('secure_action_id',sa.id,'decision',case when p_approve then 'AUTHORIZED' else 'REJECTED' end)); return a; end $$;
create or replace function public.create_authorized_sublease_right(p_authorization_id uuid) returns public.asset_rights language plpgsql security definer set search_path='' as $$ declare a public.asset_authorizations; x public.asset_rights; begin select * into a from public.asset_authorizations where id=p_authorization_id for update; if not found then raise exception 'AUTHORIZATION_NOT_FOUND'; end if; if public.can_manage_administration(a.administration_id) is not true then raise exception 'MANAGEMENT_ACCESS_REQUIRED'; end if; if a.status<>'AUTHORIZED' then raise exception 'AUTHORIZATION_NOT_APPROVED'; end if; if a.valid_from is not null and a.valid_from>current_date then raise exception 'AUTHORIZATION_NOT_YET_VALID'; end if; if a.valid_until is not null and a.valid_until<current_date then raise exception 'AUTHORIZATION_EXPIRED'; end if; insert into public.asset_rights(administration_id,rental_subject_id,person_id,right_type,status,source_relationship_id,authorization_id,valid_from,valid_until) values(a.administration_id,a.rental_subject_id,a.grantee_person_id,'AUTHORIZED_SUBLEASE','ACTIVE',a.source_relationship_id,a.id,a.valid_from,a.valid_until) returning * into x; return x; end $$;
revoke all on function public.request_parking_sublease_authorization(uuid,uuid,uuid,uuid,text,timestamptz,date,date),public.decide_parking_sublease_authorization(text,boolean,text),public.create_authorized_sublease_right(uuid) from public,anon;
grant execute on function public.request_parking_sublease_authorization(uuid,uuid,uuid,uuid,text,timestamptz,date,date),public.decide_parking_sublease_authorization(text,boolean,text),public.create_authorized_sublease_right(uuid) to authenticated,service_role;